server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  r2dbc:
    url: 'r2dbc:postgresql://postgresdb:5432/localdb?schema=demo'
    username: 'postgres'
    password: 'password'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://registry-server:8002/eureka/'
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
