server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  r2dbc:
    url: 'r2dbc:postgresql://localhost:5432/localdb?schema=demo'
    username: 'postgres'
    password: 'password'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8002/eureka/'
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}

resilience4j.circuitbreaker:
  configs:
    instances:
      account-microservice:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        slidingWindowType: TIME_BASED
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 2s
        failureRateThreshold: 30
        eventConsumerBufferSize: 10

resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 2
      waitDuration: 100
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException

resilience4j.bulkhead:
  configs:
    default:
      maxConcurrentCalls: 100

resilience4j.thread-pool-bulkhead:
  configs:
    default:
      maxThreadPoolSize: 4
      coreThreadPoolSize: 2
      queueCapacity: 2

resilience4j.ratelimiter:
  configs:
    default:
      registerHealthIndicator: false
      limitForPeriod: 10
      limitRefreshPeriod: 1s
      timeoutDuration: 0
      eventConsumerBufferSize: 100

application:
  http-client:
    account:
      base-url: 'http://localhost:8080/api/accounts'