server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  r2dbc:
    url: 'r2dbc:postgresql://localhost:5432/localdb?schema=demo'
    username: 'postgres'
    password: 'password'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8002/eureka/'
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}

resilience4j.circuitbreaker:
  instances:
    account-microservice:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 50s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

resilience4j.retry:
  instances:
    account-microservice:
      maxAttempts: 3
      waitDuration: 10s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2

application:
  http-client:
    account:
      base-url: 'http://localhost:8080/api/accounts'
