server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: 'http://localhost:8002/eureka/'
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: currency-microservice
          uri: lb://currency-microservice
          predicates:
            - Path=/currency/microservice/**
        - id: account-microservice
          uri: lb://account-microservice
          predicates:
            - Path=/api/accounts/**