spring:
  application:
    name: microservice
    
  r2dbc:
    url: 'r2dbc:postgresql:http://localhost:5432/localdb?schema=demo'
    username: 'postgres'
    password: 'password'

logging:
  level:
    org:
      springframework:
        r2dbc: 'DEBUG'

server:
  port: 8003