spring:
  application:
    name: microservice
    
  r2dbc:
    url: 'r2dbc:postgresql://localhost:5432/localdb?schema=demo'
    username: 'postgres'
    password: 'password'
    
server:
  port: 8003

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8002/eureka/'
